sudo: required
services:
  - docker

before_install:
  - docker build -t adocker123adocker/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true adocker123adocker/react-test npm test

after_success:
  - docker build -t freulein/multi-client ./client
  - docker build -t freulein/multi-nginx ./nginx
  - docker build -t freulein/multi-server ./server
  - docker build -t freulein/multi-worker ./worker
  # log in to the docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin docker.io
  # Take those images to docker hub
  - docker push freulein/multi-client
  - docker push freulein/multi-nginx
  - docker push freulein/multi-server
  - docker push freulein/multi-worker 

